version: '2.1'
services:
  ipfs:
    image: ipfs/kubo:latest
    restart: always
    environment:
      - IPFS_PATH=/data/ipfs
    network_mode: host
    command: ["daemon", "--migrate=true", "--agent-version-suffix=docker", "--enable-gc"]
    volumes:
      - ipfs:/data/ipfs
      - ./ipfs-init.sh:/container-init.d/ipfs-init.sh
    container_name: ipfs
  poa:
    image: disregardfiat/poa:0.0.2
    restart: always
    command: ["./main", "-node", "2", "-username", "${ACCOUNT}", "-WS_PORT=8002", "-useWS=true", "-honeycomb=true", "-IPFS_PORT=5001", "-validators", "https://spktest.dlux.io/services/VAL"]
    network_mode: host
    container_name: poa
  api:
    build: .
    restart: always
    environment:
      - PORT=5050
      - ENDPOINT=127.0.0.1
      - ENDPORT=5001
      - DOCKER=true
    network_mode: host
    volumes:
      - ./.env:/.env
      - db:/db/
    logging:
      options:
        max-size: "2m"
        max-file: "3"
    stdin_open: true
    tty: true
volumes:
  ipfs:
    driver: local
  db:
    driver: local